# Generated by Django 3.2.12 on 2022-03-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='parent_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
